# Glosario de ejercicios resueltos: Computación Numérica 🔢

Este glosario reúne **20 ejercicios resueltos** de problemas de ingeniería. Cada ejercicio presenta primero el **enunciado** (contexto, requerimientos y ejemplo de ejecución) y, justo debajo, una **posible solución**.

**Temas que se practican:** arreglos de NumPy de una y más dimensiones (creación, tipos, indexación, *slicing*, recorrido y mutabilidad), indexación booleana y filtros, ordenamiento y combinación de arreglos, operaciones vectorizadas y funciones de agregación, operaciones por filas y columnas (`axis`), álgebra lineal (producto matricial, transpuesta, diagonal, inversa y sistemas de ecuaciones) y *broadcasting*.

```{tip}
Intente resolver cada ejercicio **antes** de leer la solución. La regla de oro de esta lección: si está a punto de escribir un ciclo `for` para recorrer los elementos de un arreglo, pregúntese primero si existe una **operación vectorizada** que haga lo mismo.
```

```{note}
Todas las soluciones importan NumPy con el alias convencional (`import numpy as np`) y siguen la estructura del curso: funciones auxiliares, `main()` y la invocación `main()`. Los ejercicios con números aleatorios fijan la semilla para que el resultado sea reproducible.
```

## 📑 Índice de ejercicios

| # | Ejercicio | Temas |
| :-: | :-- | :-- |
| 1 | [Termopares de un horno de fundición](#ejercicio-10-1-termopares-de-un-horno-de-fundici-n) | Creación de arreglos, operaciones vectorizadas, filtros booleanos |
| 2 | [Perfil de velocidades en una tubería](#ejercicio-10-2-perfil-de-velocidades-en-una-tuber-a) | `np.linspace`, operaciones vectorizadas, `np.sum` |
| 3 | [Consumo eléctrico por hora de una fábrica](#ejercicio-10-3-consumo-el-ctrico-por-hora-de-una-f-brica) | `np.arange`, `np.where`, indexación booleana, agregación |
| 4 | [Esfuerzos en las barras de una armadura](#ejercicio-10-4-esfuerzos-en-las-barras-de-una-armadura) | Operaciones elemento a elemento entre arreglos, `np.abs`, filtros |
| 5 | [Producción de tres plantas de concreto](#ejercicio-10-5-producci-n-de-tres-plantas-de-concreto) | Arreglos 2D, agregación con `axis`, `argmax` por filas |
| 6 | [Corrientes de malla en un circuito](#ejercicio-10-6-corrientes-de-malla-en-un-circuito) | Sistemas de ecuaciones lineales con `np.linalg.solve`, producto matricial |
| 7 | [Mezcla de aleaciones de bronce](#ejercicio-10-7-mezcla-de-aleaciones-de-bronce) | Planteamiento y solución de un sistema lineal |
| 8 | [Rotación de una pieza en una máquina CNC](#ejercicio-10-8-rotaci-n-de-una-pieza-en-una-m-quina-cnc) | Matrices de transformación, producto matricial, *broadcasting* |
| 9 | [Asignación de pozos a plantas de tratamiento](#ejercicio-10-9-asignaci-n-de-pozos-a-plantas-de-tratamiento) | *Broadcasting* en 2D, `argmin` por filas |
| 10 | [Llenado acumulado de un tanque de retención](#ejercicio-10-10-llenado-acumulado-de-un-tanque-de-retenci-n) | `np.cumsum`, búsqueda con máscaras, exploración de documentación |
| 11 | [Limpieza del registro de un acelerógrafo](#ejercicio-10-11-limpieza-del-registro-de-un-aceler-grafo) | Mutabilidad: `np.delete`, `np.insert`, `np.where` |
| 12 | [Movimiento de tierras en un terreno](#ejercicio-10-12-movimiento-de-tierras-en-un-terreno) | Matrices, `np.where`, suma con máscaras |
| 13 | [Selección de proveedores de rodamientos](#ejercicio-10-13-selecci-n-de-proveedores-de-rodamientos) | `np.argsort`, ordenamiento, normalización con operaciones vectorizadas |
| 14 | [Evolución de la resistencia del concreto](#ejercicio-10-14-evoluci-n-de-la-resistencia-del-concreto) | Estadísticas por columnas, *broadcasting* fila-columna |
| 15 | [Tolerancias acumuladas en un ensamble](#ejercicio-10-15-tolerancias-acumuladas-en-un-ensamble) | Arreglos aleatorios con semilla, filtros, porcentajes |
| 16 | [Calibración de un acelerómetro de tres ejes](#ejercicio-10-16-calibraci-n-de-un-aceler-metro-de-tres-ejes) | Matriz inversa, producto matricial, `np.diag` |
| 17 | [Revisión de una matriz de rigidez](#ejercicio-10-17-revisi-n-de-una-matriz-de-rigidez) | Transpuesta, diagonal, `np.allclose`, `np.linalg.det` |
| 18 | [Valor eficaz de un voltaje alterno](#ejercicio-10-18-valor-eficaz-de-un-voltaje-alterno) | Funciones vectoriales (`np.sin`, `np.sqrt`), `np.linspace` |
| 19 | [Interpolación en una tabla de vapor](#ejercicio-10-19-interpolaci-n-en-una-tabla-de-vapor) | `np.interp`, exploración de documentación |
| 20 | [Monitoreo estructural de un puente](#ejercicio-10-20-monitoreo-estructural-de-un-puente) | Integrado: matrices, *broadcasting*, `axis`, filtros y ordenamiento |

---

<span id="ejercicio-10-1-termopares-de-un-horno-de-fundici-n"></span>

## Ejercicio 10.1 — Termopares de un horno de fundición

Un horno de fundición de aluminio tiene varios **termopares** distribuidos en su interior. El sistema de adquisición entrega las lecturas en °C, pero el reporte para el cliente extranjero debe estar en **°F** y el modelo térmico usa **kelvin**.

Escriba un programa en Python que use NumPy y:

A. Defina `leer_arreglo(mensaje: str) -> np.ndarray`, que lee números separados por espacios y los retorna como un arreglo de `float`.

B. Defina `convertir_temperaturas(celsius: np.ndarray) -> tuple[np.ndarray, np.ndarray]`, que retorna los arreglos en °F y en K **sin usar ciclos**.

C. En `main()`, lea las lecturas y la temperatura mínima de colada (°C). Muestre los tres arreglos redondeados a 1 decimal (`np.round`), el promedio, la lectura máxima con el **número de termopar** (use `np.argmax`, numerando desde 1), y los números de los termopares que están **por debajo** de la temperatura de colada (use indexación booleana con `np.arange`).

**Ejemplo de ejecución**

*Lo que aparece en **negrita** corresponde a lo que digita la persona usuaria.*

<pre>
Lecturas de los termopares (°C): <b>712.5 698.0 721.3 684.9 705.2 690.4</b>
Temperatura mínima de colada (°C): <b>695</b>

°C: [712.5 698.  721.3 684.9 705.2 690.4]
°F: [1314.5 1288.4 1330.3 1264.8 1301.4 1274.7]
K:  [985.6 971.2 994.4 958.  978.4 963.6]
Promedio: 702.1 °C
Máxima: 721.3 °C en el termopar 3
Termopares bajo la temperatura de colada: [4 6]
</pre>

In [ ]:
#@title Solución
import numpy as np


def leer_arreglo(mensaje: str) -> np.ndarray:
    """Lee números separados por espacios y los retorna como arreglo."""
    return np.array(input(mensaje).split(), dtype=float)


def convertir_temperaturas(celsius: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """Convierte un arreglo de °C a °F y a K."""
    return celsius * 9 / 5 + 32, celsius + 273.15


def main() -> None:
    celsius = leer_arreglo("Lecturas de los termopares (°C): ")
    temperatura_colada = float(input("Temperatura mínima de colada (°C): "))

    fahrenheit, kelvin = convertir_temperaturas(celsius)
    numeros = np.arange(1, len(celsius) + 1)
    frios = numeros[celsius < temperatura_colada]

    print(f"\n°C: {np.round(celsius, 1)}")
    print(f"°F: {np.round(fahrenheit, 1)}")
    print(f"K:  {np.round(kelvin, 1)}")
    print(f"Promedio: {celsius.mean():.1f} °C")
    print(f"Máxima: {celsius.max():.1f} °C en el termopar {np.argmax(celsius) + 1}")
    print(f"Termopares bajo la temperatura de colada: {frios}")


main()

**Explicación**

`celsius * 9 / 5 + 32` se aplica a **todos** los elementos a la vez: es la operación vectorizada que reemplaza un ciclo `for`. La expresión `celsius < temperatura_colada` produce un arreglo de booleanos del mismo tamaño, que se usa como **máscara** para quedarse solo con los números de termopar donde la condición es `True`.

---

<span id="ejercicio-10-2-perfil-de-velocidades-en-una-tuber-a"></span>

## Ejercicio 10.2 — Perfil de velocidades en una tubería

En un flujo **laminar** dentro de una tubería, la velocidad del fluido no es uniforme: es máxima en el centro y cero en la pared. El perfil es parabólico:

$$v(r) = v_{max} \left(1 - \left(\frac{r}{R}\right)^2\right)$$

donde $r$ es la distancia al centro y $R$ el radio interno. La velocidad **promedio** teórica es $v_{max} / 2$.

Escriba un programa en Python que use NumPy y:

A. Defina `calcular_perfil(velocidad_maxima: float, radio: float, puntos: int) -> tuple[np.ndarray, np.ndarray]`, que usa `np.linspace` para generar las posiciones radiales desde 0 hasta $R$ y retorna las posiciones y las velocidades.

B. Defina `estimar_caudal(posiciones: np.ndarray, velocidades: np.ndarray) -> float`: aproxima el caudal dividiendo la sección en anillos delgados de área $2\pi r \Delta r$ y sumando $v \cdot 2\pi r \Delta r$ con `np.sum` (sin ciclos).

C. En `main()`, solicite $v_{max}$ (m/s), el diámetro interno (mm) y la cantidad de puntos. Muestre una tabla con 6 posiciones equiespaciadas (use *slicing* con paso) y sus velocidades, el caudal estimado (L/s) y el caudal teórico $Q = \frac{v_{max}}{2} \pi R^2$ (L/s), con el error porcentual entre ambos.

**Ejemplo de ejecución**

*Lo que aparece en **negrita** corresponde a lo que digita la persona usuaria.*

<pre>
Velocidad máxima (m/s): <b>0.8</b>
Diámetro interno (mm): <b>50</b>
Cantidad de puntos: <b>1001</b>

  r (mm)   v (m/s)
    0.00     0.800
    5.00     0.768
   10.00     0.672
   15.00     0.512
   20.00     0.288
   25.00     0.000

Caudal estimado: 0.7854 L/s
Caudal teórico: 0.7854 L/s
Error: 0.000%
</pre>

In [ ]:
#@title Solución
import numpy as np


def calcular_perfil(velocidad_maxima: float, radio: float, puntos: int) -> tuple[np.ndarray, np.ndarray]:
    """Retorna las posiciones radiales y las velocidades del perfil laminar."""
    posiciones = np.linspace(0, radio, puntos)
    velocidades = velocidad_maxima * (1 - (posiciones / radio) ** 2)
    return posiciones, velocidades


def estimar_caudal(posiciones: np.ndarray, velocidades: np.ndarray) -> float:
    """Aproxima el caudal sumando la contribución de anillos delgados."""
    delta_r = posiciones[1] - posiciones[0]
    return float(np.sum(velocidades * 2 * np.pi * posiciones * delta_r))


def main() -> None:
    velocidad_maxima = float(input("Velocidad máxima (m/s): "))
    diametro_mm = float(input("Diámetro interno (mm): "))
    puntos = int(input("Cantidad de puntos: "))

    radio = diametro_mm / 2000
    posiciones, velocidades = calcular_perfil(velocidad_maxima, radio, puntos)

    paso = (puntos - 1) // 5
    print("\n  r (mm)   v (m/s)")
    for r, v in zip(posiciones[::paso], velocidades[::paso]):
        print(f"{r * 1000:8.2f}  {v:8.3f}")

    caudal_estimado = estimar_caudal(posiciones, velocidades) * 1000
    caudal_teorico = velocidad_maxima / 2 * np.pi * radio ** 2 * 1000
    error = abs(caudal_estimado - caudal_teorico) / caudal_teorico * 100

    print(f"\nCaudal estimado: {caudal_estimado:.4f} L/s")
    print(f"Caudal teórico: {caudal_teorico:.4f} L/s")
    print(f"Error: {error:.3f}%")


main()

**Explicación**

`np.linspace(0, radio, puntos)` incluye **ambos** extremos, a diferencia de `np.arange`. Con 1001 puntos el paso es tal que `posiciones[::200]` toma exactamente 6 valores (0, 200, ..., 1000). El error es muy pequeño y disminuye al aumentar la cantidad de puntos: la suma se acerca a la integral.

---

<span id="ejercicio-10-3-consumo-el-ctrico-por-hora-de-una-f-brica"></span>

## Ejercicio 10.3 — Consumo eléctrico por hora de una fábrica

La compañía eléctrica cobra la energía de una fábrica con **tarifa horaria**: las horas **punta** (de 10:00 a 12:59 y de 17:00 a 19:59) cuestan ₡128 por kWh, y el resto de las horas ₡62 por kWh. El medidor inteligente registra el consumo (kWh) de cada una de las 24 horas del día.

Escriba un programa en Python que use NumPy y:

A. Defina `crear_tarifas() -> np.ndarray`: crea un arreglo con las 24 horas usando `np.arange(24)` y, con `np.where` y operadores lógicos de NumPy (`&`, `|`), retorna la tarifa de cada hora.

B. Defina `analizar_consumo(consumo: np.ndarray, tarifas: np.ndarray) -> tuple[float, float, float]`, que retorna el costo total, la energía consumida en horas punta y el porcentaje del costo que corresponde a las horas punta.

C. En `main()`, lea los 24 consumos (valide la cantidad), muestre el consumo total, la hora de mayor demanda, el costo total, la energía en punta y su porcentaje del costo, y cuánto se **ahorraría** si el consumo de las horas punta se trasladara a horas normales.

**Ejemplo de ejecución**

*Lo que aparece en **negrita** corresponde a lo que digita la persona usuaria.*

<pre>
Consumo de las 24 horas (kWh): <b>45 42 40 41 44 60 95 140 180 195 210 215 205 170 185 190 188 200 196 150 110 80 60 50</b>

Consumo total: 3,091.0 kWh
Hora de mayor demanda: 11:00 (215.0 kWh)
Costo total: ₡269,258
Energía en horas punta: 1,176.0 kWh (55.9% del costo)
Ahorro posible trasladando la carga: ₡77,616
</pre>

**Pregunta de respuesta corta**

¿Por qué se usan `&` y `|` en lugar de `and` y `or` para combinar las condiciones sobre el arreglo `horas`?

In [ ]:
#@title Solución
import numpy as np

TARIFA_PUNTA = 128
TARIFA_NORMAL = 62


def crear_tarifas() -> np.ndarray:
    """Retorna la tarifa (₡/kWh) de cada una de las 24 horas del día."""
    horas = np.arange(24)
    es_punta = ((horas >= 10) & (horas <= 12)) | ((horas >= 17) & (horas <= 19))
    return np.where(es_punta, TARIFA_PUNTA, TARIFA_NORMAL)


def analizar_consumo(consumo: np.ndarray, tarifas: np.ndarray) -> tuple[float, float, float]:
    """Retorna el costo total, la energía en punta y el porcentaje del costo en punta."""
    costos = consumo * tarifas
    es_punta = tarifas == TARIFA_PUNTA
    costo_total = costos.sum()
    return costo_total, consumo[es_punta].sum(), costos[es_punta].sum() / costo_total * 100


def main() -> None:
    consumo = np.array(input("Consumo de las 24 horas (kWh): ").split(), dtype=float)

    if consumo.size != 24:
        print(f"Error: se esperaban 24 valores y se recibieron {consumo.size}.")
    else:
        tarifas = crear_tarifas()
        costo_total, energia_punta, porcentaje_punta = analizar_consumo(consumo, tarifas)
        ahorro = energia_punta * (TARIFA_PUNTA - TARIFA_NORMAL)

        print(f"\nConsumo total: {consumo.sum():,.1f} kWh")
        print(f"Hora de mayor demanda: {np.argmax(consumo)}:00 ({consumo.max()} kWh)")
        print(f"Costo total: ₡{costo_total:,.0f}")
        print(f"Energía en horas punta: {energia_punta:,.1f} kWh ({porcentaje_punta:.1f}% del costo)")
        print(f"Ahorro posible trasladando la carga: ₡{ahorro:,.0f}")


main()

**Explicación**

**Respuesta corta:** `and` y `or` trabajan con **un solo** valor booleano, y aplicados a un arreglo producen `ValueError: The truth value of an array with more than one element is ambiguous`. `&` y `|` aplican la operación lógica **elemento a elemento**. Como tienen mayor precedencia que las comparaciones, cada comparación debe ir entre paréntesis.

---

<span id="ejercicio-10-4-esfuerzos-en-las-barras-de-una-armadura"></span>

## Ejercicio 10.4 — Esfuerzos en las barras de una armadura

Un análisis estructural de una **armadura de techo** de acero entrega la fuerza axial (kN) de cada barra: positiva si está en **tracción** y negativa si está en **compresión**. Cada barra tiene su propia área transversal:

```python
FUERZAS_KN = np.array([48.5, -62.3, 35.0, -18.7, 71.2, -55.8, 12.4, -40.1])
AREAS_MM2 = np.array([450, 600, 450, 300, 600, 600, 300, 450])
```

El esfuerzo es $\sigma = F / A$ (N/mm² = MPa). El acero tiene un esfuerzo admisible de **140 MPa** en tracción y de **100 MPa** en compresión (menor, por el riesgo de pandeo).

Escriba un programa en Python con las funciones:

A. `calcular_esfuerzos(fuerzas_kn: np.ndarray, areas_mm2: np.ndarray) -> np.ndarray`

B. `calcular_factores_seguridad(esfuerzos: np.ndarray) -> np.ndarray`: usa `np.where` para dividir el admisible correspondiente (tracción o compresión) entre el valor absoluto del esfuerzo.

C. `main() -> None`: muestra una tabla con cada barra (numeradas desde 1), su tipo de esfuerzo, el esfuerzo (MPa, 1 decimal) y su factor de seguridad (2 decimales); luego la barra **más crítica** (menor factor de seguridad) y las barras que **fallan** (factor menor que 1).

**Ejemplo de ejecución**

<pre>
Barra  Tipo          σ (MPa)    FS
    1  tracción        107.8   1.30
    2  compresión     -103.8   0.96
    3  tracción         77.8   1.80
    4  compresión      -62.3   1.60
    5  tracción        118.7   1.18
    6  compresión      -93.0   1.08
    7  tracción         41.3   3.39
    8  compresión      -89.1   1.12

Barra más crítica: 2 (FS = 0.96)
Barras que fallan: [2]
</pre>

In [ ]:
#@title Solución
import numpy as np

FUERZAS_KN = np.array([48.5, -62.3, 35.0, -18.7, 71.2, -55.8, 12.4, -40.1])
AREAS_MM2 = np.array([450, 600, 450, 300, 600, 600, 300, 450])
ADMISIBLE_TRACCION = 140
ADMISIBLE_COMPRESION = 100


def calcular_esfuerzos(fuerzas_kn: np.ndarray, areas_mm2: np.ndarray) -> np.ndarray:
    """Calcula el esfuerzo axial (MPa) de cada barra."""
    return fuerzas_kn * 1000 / areas_mm2


def calcular_factores_seguridad(esfuerzos: np.ndarray) -> np.ndarray:
    """Calcula el factor de seguridad de cada barra según su tipo de esfuerzo."""
    admisibles = np.where(esfuerzos >= 0, ADMISIBLE_TRACCION, ADMISIBLE_COMPRESION)
    return admisibles / np.abs(esfuerzos)


def main() -> None:
    esfuerzos = calcular_esfuerzos(FUERZAS_KN, AREAS_MM2)
    factores = calcular_factores_seguridad(esfuerzos)

    print("Barra  Tipo          σ (MPa)    FS")
    for numero, (esfuerzo, factor) in enumerate(zip(esfuerzos, factores), start=1):
        tipo = "tracción" if esfuerzo >= 0 else "compresión"
        print(f"{numero:5d}  {tipo:<12}{esfuerzo:9.1f}{factor:7.2f}")

    barras = np.arange(1, len(esfuerzos) + 1)
    print(f"\nBarra más crítica: {np.argmin(factores) + 1} (FS = {factores.min():.2f})")
    print(f"Barras que fallan: {barras[factores < 1]}")


main()

**Explicación**

Las operaciones entre dos arreglos del **mismo tamaño** se hacen posición por posición: la fuerza de la barra 3 se divide entre el área de la barra 3. Observe que la barra 2 falla aunque su fuerza (62.3 kN) es menor que la de la barra 5 (71.2 kN), porque trabaja a **compresión**, que tiene un admisible menor.

---

<span id="ejercicio-10-5-producci-n-de-tres-plantas-de-concreto"></span>

## Ejercicio 10.5 — Producción de tres plantas de concreto

Una empresa tiene **tres plantas** de concreto premezclado y registra la producción mensual (m³) del primer semestre en una matriz, donde cada **fila** es una planta y cada **columna** un mes:

```python
PLANTAS = ["Cartago", "Alajuela", "Liberia"]
MESES = ["Ene", "Feb", "Mar", "Abr", "May", "Jun"]
PRODUCCION = np.array([
    [4200, 3950, 4580, 4700, 5120, 4890],
    [3800, 4100, 3920, 4350, 4400, 4610],
    [2900, 3150, 3300, 3100, 2750, 2600],
])
```

Escriba un programa en Python con las funciones:

A. `resumir_por_planta(produccion: np.ndarray) -> tuple[np.ndarray, np.ndarray]`: total y mes de mayor producción (índice) de cada planta, usando `axis=1`.

B. `resumir_por_mes(produccion: np.ndarray) -> np.ndarray`: producción total de la empresa en cada mes, usando `axis=0`.

C. `main() -> None`: muestra, para cada planta, su total semestral, su mejor mes y su **crecimiento** porcentual de enero a junio (use *slicing* de columnas). Luego muestra el total por mes, el mes de mayor producción de la empresa y la **participación** porcentual de cada planta en el total del semestre.

**Ejemplo de ejecución**

<pre>
Planta     Total (m³)  Mejor mes  Crecimiento  Participación
Cartago        27,440        May       +16.4%          39.0%
Alajuela       25,180        Jun       +21.3%          35.8%
Liberia        17,800        Mar       -10.3%          25.3%

Total por mes: [10900 11200 11800 12150 12270 12100]
Mes de mayor producción: May (12,270 m³)
</pre>

**Pregunta de respuesta corta**

¿Qué forma (`shape`) tienen `PRODUCCION.sum(axis=0)` y `PRODUCCION.sum(axis=1)`? ¿Qué dimensión "desaparece" en cada caso?

In [ ]:
#@title Solución
import numpy as np

PLANTAS = ["Cartago", "Alajuela", "Liberia"]
MESES = ["Ene", "Feb", "Mar", "Abr", "May", "Jun"]
PRODUCCION = np.array([
    [4200, 3950, 4580, 4700, 5120, 4890],
    [3800, 4100, 3920, 4350, 4400, 4610],
    [2900, 3150, 3300, 3100, 2750, 2600],
])


def resumir_por_planta(produccion: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """Retorna el total y el índice del mejor mes de cada planta."""
    return produccion.sum(axis=1), produccion.argmax(axis=1)


def resumir_por_mes(produccion: np.ndarray) -> np.ndarray:
    """Retorna la producción total de la empresa en cada mes."""
    return produccion.sum(axis=0)


def main() -> None:
    totales, mejores_meses = resumir_por_planta(PRODUCCION)
    crecimientos = (PRODUCCION[:, -1] - PRODUCCION[:, 0]) / PRODUCCION[:, 0] * 100
    participaciones = totales / totales.sum() * 100

    print("Planta     Total (m³)  Mejor mes  Crecimiento  Participación")
    for i, planta in enumerate(PLANTAS):
        print(f"{planta:<10}{totales[i]:11,}  {MESES[mejores_meses[i]]:>9}"
              f"  {crecimientos[i]:+10.1f}%  {participaciones[i]:12.1f}%")

    por_mes = resumir_por_mes(PRODUCCION)
    print(f"\nTotal por mes: {por_mes}")
    print(f"Mes de mayor producción: {MESES[np.argmax(por_mes)]} ({por_mes.max():,} m³)")


main()

**Explicación**

**Respuesta corta:** la matriz tiene forma `(3, 6)`. `sum(axis=0)` recorre las **filas** (colapsa el eje 0) y da forma `(6,)`: un total por **mes**. `sum(axis=1)` recorre las **columnas** (colapsa el eje 1) y da forma `(3,)`: un total por **planta**. El eje que se indica es el que desaparece.

---

<span id="ejercicio-10-6-corrientes-de-malla-en-un-circuito"></span>

## Ejercicio 10.6 — Corrientes de malla en un circuito

Un circuito de corriente directa tiene **tres mallas**. Aplicando la ley de voltajes de Kirchhoff se obtiene el sistema $R \cdot I = V$:

$$\begin{bmatrix} R_1 + R_2 & -R_2 & 0 \\ -R_2 & R_2 + R_3 + R_4 & -R_4 \\ 0 & -R_4 & R_4 + R_5 \end{bmatrix} \begin{bmatrix} I_1 \\ I_2 \\ I_3 \end{bmatrix} = \begin{bmatrix} V_1 \\ 0 \\ -V_2 \end{bmatrix}$$

Escriba un programa en Python que use NumPy y:

A. Defina `construir_sistema(resistencias: np.ndarray, v1: float, v2: float) -> tuple[np.ndarray, np.ndarray]`, que arma la matriz $R$ (3×3) y el vector $V$ a partir de las 5 resistencias.

B. Defina `resolver_corrientes(matriz: np.ndarray, vector: np.ndarray) -> np.ndarray` con `np.linalg.solve`.

C. En `main()`, solicite las 5 resistencias (Ω) en una línea y los dos voltajes (V). Muestre la matriz, las corrientes de malla (mA, 2 decimales), la corriente por $R_2$ ($I_1 - I_2$) y por $R_4$ ($I_2 - I_3$), y **verifique** la solución calculando `matriz @ corrientes` y comparándola con $V$ mediante `np.allclose`.

**Ejemplo de ejecución**

*Lo que aparece en **negrita** corresponde a lo que digita la persona usuaria.*

<pre>
Resistencias R1 a R5 (Ω): <b>100 220 150 330 470</b>
Voltaje V1 (V): <b>12</b>
Voltaje V2 (V): <b>9</b>

Matriz de resistencias:
[[ 320. -220.    0.]
 [-220.  700. -330.]
 [   0. -330.  800.]]
Corrientes de malla (mA): [45.06 11.   -6.71]
Corriente por R2: 34.06 mA
Corriente por R4: 17.71 mA
¿La solución satisface R · I = V?: True
</pre>

In [ ]:
#@title Solución
import numpy as np


def construir_sistema(resistencias: np.ndarray, v1: float, v2: float) -> tuple[np.ndarray, np.ndarray]:
    """Arma la matriz de resistencias y el vector de voltajes del circuito."""
    r1, r2, r3, r4, r5 = resistencias
    matriz = np.array([
        [r1 + r2, -r2, 0],
        [-r2, r2 + r3 + r4, -r4],
        [0, -r4, r4 + r5],
    ])
    vector = np.array([v1, 0, -v2])
    return matriz, vector


def resolver_corrientes(matriz: np.ndarray, vector: np.ndarray) -> np.ndarray:
    """Resuelve el sistema R · I = V."""
    return np.linalg.solve(matriz, vector)


def main() -> None:
    resistencias = np.array(input("Resistencias R1 a R5 (Ω): ").split(), dtype=float)
    v1 = float(input("Voltaje V1 (V): "))
    v2 = float(input("Voltaje V2 (V): "))

    matriz, vector = construir_sistema(resistencias, v1, v2)
    corrientes = resolver_corrientes(matriz, vector)
    corrientes_ma = corrientes * 1000

    print(f"\nMatriz de resistencias:\n{matriz}")
    print(f"Corrientes de malla (mA): {np.round(corrientes_ma, 2)}")
    print(f"Corriente por R2: {corrientes_ma[0] - corrientes_ma[1]:.2f} mA")
    print(f"Corriente por R4: {corrientes_ma[1] - corrientes_ma[2]:.2f} mA")
    print(f"¿La solución satisface R · I = V?: {np.allclose(matriz @ corrientes, vector)}")


main()

**Explicación**

`np.linalg.solve` resuelve el sistema directamente y es más preciso y eficiente que calcular la inversa y multiplicar (`np.linalg.inv(R) @ V`). Una corriente de malla **negativa** significa simplemente que circula en sentido contrario al supuesto al plantear las ecuaciones. `np.allclose` compara con tolerancia, como corresponde al trabajar con flotantes.

---

<span id="ejercicio-10-7-mezcla-de-aleaciones-de-bronce"></span>

## Ejercicio 10.7 — Mezcla de aleaciones de bronce

Una fundición debe producir un lote de bronce con una composición exacta de **cobre**, **estaño** y **zinc**, fundiendo juntas tres aleaciones que tiene en inventario. La composición (fracción en masa) de cada aleación es:

| Elemento | Aleación A | Aleación B | Aleación C |
| :-- | :-: | :-: | :-: |
| Cobre | 0.90 | 0.70 | 0.60 |
| Estaño | 0.10 | 0.05 | 0.10 |
| Zinc | 0.00 | 0.25 | 0.30 |

Si se usan $m_A$, $m_B$ y $m_C$ kg de cada aleación, la masa de cobre en el lote es $0.90 m_A + 0.70 m_B + 0.60 m_C$, y así con cada elemento: es un sistema de 3 ecuaciones lineales.

Escriba un programa en Python que:

A. Defina `calcular_masas(composicion: np.ndarray, masa_lote: float, objetivo: np.ndarray) -> np.ndarray`: el lado derecho del sistema es la masa de cada elemento que debe tener el lote (`masa_lote * objetivo`).

B. En `main()`, solicite la masa del lote (kg) y la composición objetivo (fracciones de Cu, Sn y Zn, que deben sumar 1). Resuelva el sistema y muestre los kg de cada aleación. Si alguna masa resulta **negativa**, indique que la composición **no se puede lograr** con esas aleaciones. Si se puede, verifique la composición obtenida con un producto matricial.

**Ejemplos de ejecución**

*Lo que aparece en **negrita** corresponde a lo que digita la persona usuaria.*

<pre>
Masa del lote (kg): <b>500</b>
Composición objetivo (Cu Sn Zn): <b>0.72 0.08 0.20</b>
Aleación A: 133.33 kg
Aleación B: 200.00 kg
Aleación C: 166.67 kg
Composición obtenida (Cu Sn Zn): [0.72 0.08 0.2 ]
</pre>

<pre>
Masa del lote (kg): <b>500</b>
Composición objetivo (Cu Sn Zn): <b>0.95 0.05 0.00</b>
Aleación A: 416.67 kg
Aleación B: 500.00 kg
Aleación C: -416.67 kg
La composición no se puede lograr con estas aleaciones (hay masas negativas).
</pre>

In [ ]:
#@title Solución
import numpy as np

ALEACIONES = ["A", "B", "C"]
COMPOSICION = np.array([
    [0.90, 0.70, 0.60],
    [0.10, 0.05, 0.10],
    [0.00, 0.25, 0.30],
])


def calcular_masas(composicion: np.ndarray, masa_lote: float, objetivo: np.ndarray) -> np.ndarray:
    """Resuelve las masas de cada aleación para lograr la composición objetivo."""
    return np.linalg.solve(composicion, masa_lote * objetivo)


def main() -> None:
    masa_lote = float(input("Masa del lote (kg): "))
    objetivo = np.array(input("Composición objetivo (Cu Sn Zn): ").split(), dtype=float)

    if not np.isclose(objetivo.sum(), 1):
        print("Error: las fracciones deben sumar 1.")
    else:
        masas = calcular_masas(COMPOSICION, masa_lote, objetivo)
        for aleacion, masa in zip(ALEACIONES, masas):
            print(f"Aleación {aleacion}: {masa:.2f} kg")

        if np.any(masas < 0):
            print("La composición no se puede lograr con estas aleaciones (hay masas negativas).")
        else:
            composicion_obtenida = COMPOSICION @ masas / masas.sum()
            print(f"Composición obtenida (Cu Sn Zn): {np.round(composicion_obtenida, 4)}")


main()

**Explicación**

La matemática puede dar una solución que **no tiene sentido físico**: no se puede fundir una masa negativa. Revisar si el resultado es razonable es parte de la **validación** de cualquier programa de ingeniería. `np.any(masas < 0)` responde en una sola instrucción si **al menos un** elemento cumple la condición.

---

<span id="ejercicio-10-8-rotaci-n-de-una-pieza-en-una-m-quina-cnc"></span>

## Ejercicio 10.8 — Rotación de una pieza en una máquina CNC

El programa de una **fresadora CNC** describe el contorno de una pieza con los vértices $(x, y)$ en mm. Para mecanizar la pieza en otra posición de la mesa, hay que **rotarla** un ángulo $\theta$ alrededor del origen y luego **trasladarla**:

$$\begin{bmatrix} x' \\ y' \end{bmatrix} = \begin{bmatrix} \cos\theta & -\sin\theta \\ \sin\theta & \cos\theta \end{bmatrix} \begin{bmatrix} x \\ y \end{bmatrix} + \begin{bmatrix} d_x \\ d_y \end{bmatrix}$$

Escriba un programa en Python que use NumPy y:

A. Defina `matriz_rotacion(angulo_grados: float) -> np.ndarray` (use `np.radians`, `np.cos`, `np.sin`).

B. Defina `transformar(vertices: np.ndarray, angulo_grados: float, desplazamiento: np.ndarray) -> np.ndarray`: `vertices` es una matriz de forma `(n, 2)`; aplique la rotación a **todos** los vértices con un solo producto matricial (use la **transpuesta**) y sume el desplazamiento aprovechando el *broadcasting*.

C. En `main()`, use los vértices de una placa en L: `[[0, 0], [60, 0], [60, 20], [20, 20], [20, 50], [0, 50]]`. Solicite el ángulo y el desplazamiento, muestre los vértices transformados (2 decimales) y verifique que las **distancias** entre vértices consecutivos no cambiaron (una rotación y una traslación no deforman la pieza).

**Ejemplo de ejecución**

*Lo que aparece en **negrita** corresponde a lo que digita la persona usuaria.*

<pre>
Ángulo de rotación (°): <b>30</b>
Desplazamiento dx dy (mm): <b>150 80</b>

Vértices transformados (mm):
[[150.    80.  ]
 [201.96 110.  ]
 [191.96 127.32]
 [157.32 107.32]
 [142.32 133.3 ]
 [125.   123.3 ]]
Lados originales: [60. 20. 40. 30. 20. 50.]
Lados transformados: [60. 20. 40. 30. 20. 50.]
¿La pieza conserva su forma?: True
</pre>

In [ ]:
#@title Solución
import numpy as np

VERTICES = np.array([[0, 0], [60, 0], [60, 20], [20, 20], [20, 50], [0, 50]], dtype=float)


def matriz_rotacion(angulo_grados: float) -> np.ndarray:
    """Retorna la matriz de rotación 2D para el ángulo indicado."""
    angulo = np.radians(angulo_grados)
    return np.array([[np.cos(angulo), -np.sin(angulo)],
                     [np.sin(angulo), np.cos(angulo)]])


def transformar(vertices: np.ndarray, angulo_grados: float, desplazamiento: np.ndarray) -> np.ndarray:
    """Rota todos los vértices y luego los traslada."""
    return vertices @ matriz_rotacion(angulo_grados).T + desplazamiento


def distancias_consecutivas(vertices: np.ndarray) -> np.ndarray:
    """Distancia entre cada vértice y el siguiente (cerrando el contorno)."""
    siguientes = np.roll(vertices, -1, axis=0)
    return np.sqrt(np.sum((siguientes - vertices) ** 2, axis=1))


def main() -> None:
    angulo = float(input("Ángulo de rotación (°): "))
    desplazamiento = np.array(input("Desplazamiento dx dy (mm): ").split(), dtype=float)

    transformados = transformar(VERTICES, angulo, desplazamiento)

    print(f"\nVértices transformados (mm):\n{np.round(transformados, 2)}")
    print(f"Lados originales: {distancias_consecutivas(VERTICES)}")
    print(f"Lados transformados: {np.round(distancias_consecutivas(transformados), 6)}")
    print(f"¿La pieza conserva su forma?: "
          f"{np.allclose(distancias_consecutivas(VERTICES), distancias_consecutivas(transformados))}")


main()

**Explicación**

Con los vértices como filas (forma `(6, 2)`), la fórmula $R \cdot v$ para cada vértice se escribe para todos a la vez como `vertices @ R.T`. Luego, sumar el arreglo `desplazamiento` de forma `(2,)` a la matriz `(6, 2)` es un caso de *broadcasting*: NumPy lo suma a **cada fila**. `np.roll` desplaza las filas para emparejar cada vértice con el siguiente.

---

<span id="ejercicio-10-9-asignaci-n-de-pozos-a-plantas-de-tratamiento"></span>

## Ejercicio 10.9 — Asignación de pozos a plantas de tratamiento

Una municipalidad tiene varios **pozos** de agua y dos **plantas de tratamiento**. Cada pozo debe enviar su agua a la planta **más cercana**. Las coordenadas (km) son:

```python
POZOS = np.array([[1.2, 3.4], [5.8, 1.1], [3.3, 6.7], [8.1, 4.4], [6.5, 7.9], [0.4, 0.8]])
PLANTAS = np.array([[2.0, 2.0], [7.0, 6.0]])
CAUDALES_LS = np.array([12, 18, 9, 22, 15, 7])  # caudal de cada pozo
```

Escriba un programa en Python que:

A. Defina `matriz_distancias(puntos_a: np.ndarray, puntos_b: np.ndarray) -> np.ndarray`, que retorna una matriz de forma `(pozos, plantas)` con todas las distancias, **sin ciclos**: agregue un eje con `puntos_a[:, np.newaxis, :]` para que la resta con `puntos_b` se expanda por *broadcasting*.

B. En `main()`, calcule la matriz de distancias (muestre redondeada a 2 decimales), asigne cada pozo a su planta más cercana con `argmin(axis=1)` y muestre para cada planta: los pozos asignados, el **caudal total** que recibe y la **longitud total** de tubería necesaria. Si una planta recibe más de **40 L/s** (su capacidad), muestre una advertencia.

**Ejemplo de ejecución**

<pre>
Distancias (km), filas = pozos, columnas = plantas:
[[1.61 6.36]
 [3.91 5.04]
 [4.88 3.77]
 [6.56 1.94]
 [7.42 1.96]
 [2.   8.4 ]]

Planta 1: pozos [1 2 6]
  Caudal recibido: 37 L/s
  Tubería necesaria: 7.52 km

Planta 2: pozos [3 4 5]
  Caudal recibido: 46 L/s
  Tubería necesaria: 7.67 km
  ¡Advertencia! Supera la capacidad de 40 L/s.
</pre>

**Pregunta de respuesta corta**

¿Qué forma tiene `POZOS[:, np.newaxis, :] - PLANTAS`? Explique cómo NumPy "estira" cada arreglo para poder restarlos.

In [ ]:
#@title Solución
import numpy as np

POZOS = np.array([[1.2, 3.4], [5.8, 1.1], [3.3, 6.7], [8.1, 4.4], [6.5, 7.9], [0.4, 0.8]])
PLANTAS = np.array([[2.0, 2.0], [7.0, 6.0]])
CAUDALES_LS = np.array([12, 18, 9, 22, 15, 7])
CAPACIDAD_LS = 40


def matriz_distancias(puntos_a: np.ndarray, puntos_b: np.ndarray) -> np.ndarray:
    """Distancias entre cada punto de A (filas) y cada punto de B (columnas)."""
    diferencias = puntos_a[:, np.newaxis, :] - puntos_b
    return np.sqrt(np.sum(diferencias ** 2, axis=2))


def main() -> None:
    distancias = matriz_distancias(POZOS, PLANTAS)
    asignacion = distancias.argmin(axis=1)
    numeros_pozo = np.arange(1, len(POZOS) + 1)

    print(f"Distancias (km), filas = pozos, columnas = plantas:\n{np.round(distancias, 2)}")
    for planta in range(len(PLANTAS)):
        asignados = asignacion == planta
        caudal = CAUDALES_LS[asignados].sum()
        tuberia = distancias[asignados, planta].sum()
        print(f"\nPlanta {planta + 1}: pozos {numeros_pozo[asignados]}")
        print(f"  Caudal recibido: {caudal} L/s")
        print(f"  Tubería necesaria: {tuberia:.2f} km")
        if caudal > CAPACIDAD_LS:
            print(f"  ¡Advertencia! Supera la capacidad de {CAPACIDAD_LS} L/s.")


main()

**Explicación**

**Respuesta corta:** `POZOS[:, np.newaxis, :]` tiene forma `(6, 1, 2)` y `PLANTAS` tiene forma `(2, 2)`, que NumPy trata como `(1, 2, 2)`. Por *broadcasting*, las dimensiones de tamaño 1 se "repiten" para coincidir, y el resultado tiene forma **`(6, 2, 2)`**: para cada pozo y cada planta, la diferencia en x y en y. Sumando los cuadrados sobre el último eje (`axis=2`) se obtiene la matriz `(6, 2)` de distancias.

---

<span id="ejercicio-10-10-llenado-acumulado-de-un-tanque-de-retenci-n"></span>

## Ejercicio 10.10 — Llenado acumulado de un tanque de retención

Un **tanque de retención pluvial** almacena temporalmente el agua de lluvia de un parqueo durante una tormenta, para no saturar el alcantarillado. Un pluviómetro registra la lluvia cada **10 minutos** (mm). El volumen que entra al tanque en cada intervalo es:

$$V = C \cdot \frac{lluvia_{mm}}{1000} \cdot A$$

con $C = 0.9$ (coeficiente de escorrentía del asfalto) y $A$ el área del parqueo (m²). Cuando termina la tormenta, una bomba vacía el tanque a un caudal constante (m³/h).

Busque en la documentación qué hace `np.cumsum` y escriba un programa en Python que:

A. Defina `calcular_volumen_acumulado(lluvia: np.ndarray, area: float, volumen_inicial: float) -> np.ndarray`: el volumen en el tanque al final de cada intervalo es el volumen inicial más la **suma acumulada** de las entradas.

B. En `main()`, lea las lecturas de lluvia, el área (m²), el volumen inicial y la capacidad del tanque (m³) y el caudal de la bomba (m³/h). Muestre el volumen acumulado (1 decimal) y, si el tanque **rebalsa**, el primer minuto en que lo hace (use `np.argmax` sobre la máscara booleana) y el volumen que se **derrama**; si no rebalsa, el porcentaje de capacidad usado. Al final, muestre cuántas horas tarda la bomba en vaciar el tanque.

**Ejemplos de ejecución**

*Lo que aparece en **negrita** corresponde a lo que digita la persona usuaria.*

<pre>
Lluvia por intervalo de 10 min (mm): <b>2.5 6.0 12.4 18.2 9.8 4.1 1.5 0.6</b>
Área del parqueo (m²): <b>3200</b>
Volumen inicial en el tanque (m³): <b>10</b>
Capacidad del tanque (m³): <b>150</b>
Caudal de la bomba (m³/h): <b>45</b>

Volumen acumulado (m³): [ 17.2  34.5  70.2 122.6 150.8 162.6 167.  168.7]
¡El tanque rebalsa a partir del minuto 50!
Volumen derramado: 18.7 m³
Tiempo de vaciado con la bomba: 3.33 h
</pre>

<pre>
Lluvia por intervalo de 10 min (mm): <b>2.5 6.0 12.4 18.2 9.8 4.1 1.5 0.6</b>
Área del parqueo (m²): <b>2000</b>
Volumen inicial en el tanque (m³): <b>10</b>
Capacidad del tanque (m³): <b>150</b>
Caudal de la bomba (m³/h): <b>45</b>

Volumen acumulado (m³): [ 14.5  25.3  47.6  80.4  98.  105.4 108.1 109.2]
El tanque no rebalsa (usa el 73% de su capacidad).
Tiempo de vaciado con la bomba: 2.43 h
</pre>

In [ ]:
#@title Solución
import numpy as np

COEFICIENTE_ESCORRENTIA = 0.9
MINUTOS_POR_INTERVALO = 10


def calcular_volumen_acumulado(lluvia: np.ndarray, area: float, volumen_inicial: float) -> np.ndarray:
    """Volumen en el tanque (m³) al final de cada intervalo de lluvia."""
    entradas = COEFICIENTE_ESCORRENTIA * lluvia / 1000 * area
    return volumen_inicial + np.cumsum(entradas)


def main() -> None:
    lluvia = np.array(input("Lluvia por intervalo de 10 min (mm): ").split(), dtype=float)
    area = float(input("Área del parqueo (m²): "))
    volumen_inicial = float(input("Volumen inicial en el tanque (m³): "))
    capacidad = float(input("Capacidad del tanque (m³): "))
    caudal_bomba = float(input("Caudal de la bomba (m³/h): "))

    volumen = calcular_volumen_acumulado(lluvia, area, volumen_inicial)
    minutos = np.arange(1, len(lluvia) + 1) * MINUTOS_POR_INTERVALO
    rebalsa = volumen > capacidad

    print(f"\nVolumen acumulado (m³): {np.round(volumen, 1)}")
    if np.any(rebalsa):
        print(f"¡El tanque rebalsa a partir del minuto {minutos[np.argmax(rebalsa)]}!")
        print(f"Volumen derramado: {volumen[-1] - capacidad:.1f} m³")
        volumen_final = capacidad
    else:
        print(f"El tanque no rebalsa (usa el {volumen[-1] / capacidad:.0%} de su capacidad).")
        volumen_final = volumen[-1]

    print(f"Tiempo de vaciado con la bomba: {volumen_final / caudal_bomba:.2f} h")


main()

**Explicación**

`np.cumsum([a, b, c])` retorna `[a, a + b, a + b + c]`: la **suma acumulada**, que es justamente el volumen almacenado intervalo tras intervalo. Aplicado a una máscara booleana, `np.argmax` retorna el índice del **primer** `True` (porque `True` vale 1 y es el máximo); por eso primero se verifica con `np.any` que exista al menos uno, ya que si todos son `False`, `argmax` retornaría 0.

---

<span id="ejercicio-10-11-limpieza-del-registro-de-un-aceler-grafo"></span>

## Ejercicio 10.11 — Limpieza del registro de un acelerógrafo

Un **acelerógrafo** instalado en un edificio registra la aceleración (en g) durante un sismo. Cuando el instrumento pierde la señal, guarda el valor **−999**. Además, el técnico sabe que al registro le falta la **primera** muestra, que por calibración vale 0.0.

Escriba un programa en Python que use NumPy y:

A. Defina `eliminar_faltantes(registro: np.ndarray, codigo_error: float) -> tuple[np.ndarray, np.ndarray]`: encuentra con `np.where` las posiciones de los datos faltantes y retorna un **nuevo** arreglo sin ellos (con `np.delete`) y las posiciones eliminadas.

B. En `main()`, lea el registro, elimine los faltantes, **inserte** con `np.insert` el valor 0.0 al inicio, y muestre: las posiciones eliminadas, el registro limpio, la aceleración pico **absoluta** (PGA) y la **intensidad** según esta escala: menos de 0.1 g `Leve`, de 0.1 a menos de 0.3 g `Moderada`, 0.3 g o más `Severa`. Verifique además que el arreglo original **no cambió** (compare su tamaño).

**Ejemplo de ejecución**

*Lo que aparece en **negrita** corresponde a lo que digita la persona usuaria.*

<pre>
Registro de aceleración (g): <b>0.012 -0.045 0.098 -999 -0.187 0.254 -0.312 -999 0.221 -0.143 0.076 -0.031</b>

Posiciones con datos faltantes: [3 7]
Registro limpio: [ 0.     0.012 -0.045  0.098 -0.187  0.254 -0.312  0.221 -0.143  0.076
 -0.031]
PGA: 0.312 g -&gt; Severa
Tamaño del original: 12, del limpio: 11
</pre>

In [ ]:
#@title Solución
import numpy as np

CODIGO_ERROR = -999


def eliminar_faltantes(registro: np.ndarray, codigo_error: float) -> tuple[np.ndarray, np.ndarray]:
    """Retorna el registro sin los datos faltantes y las posiciones eliminadas."""
    posiciones = np.where(registro == codigo_error)[0]
    return np.delete(registro, posiciones), posiciones


def main() -> None:
    registro = np.array(input("Registro de aceleración (g): ").split(), dtype=float)

    limpio, eliminadas = eliminar_faltantes(registro, CODIGO_ERROR)
    limpio = np.insert(limpio, 0, 0.0)
    pga = np.abs(limpio).max()

    if pga < 0.1:
        intensidad = "Leve"
    elif pga < 0.3:
        intensidad = "Moderada"
    else:
        intensidad = "Severa"

    print(f"\nPosiciones con datos faltantes: {eliminadas}")
    print(f"Registro limpio: {limpio}")
    print(f"PGA: {pga} g -> {intensidad}")
    print(f"Tamaño del original: {registro.size}, del limpio: {limpio.size}")


main()

**Explicación**

A diferencia del método `append` de las listas, `np.delete` y `np.insert` **no modifican** el arreglo original: retornan un arreglo **nuevo**, porque un arreglo de NumPy tiene un tamaño fijo en memoria. Por eso hay que asignar el resultado (`limpio = np.insert(...)`). El PGA se calcula con el valor **absoluto**, porque una aceleración de −0.312 g es tan fuerte como una de +0.312 g.

---

<span id="ejercicio-10-12-movimiento-de-tierras-en-un-terreno"></span>

## Ejercicio 10.12 — Movimiento de tierras en un terreno

Para construir una bodega, el terreno debe quedar **plano** a una cota de diseño. Un levantamiento topográfico mide la elevación (m) del terreno natural en una cuadrícula de celdas de **10 m × 10 m**:

```python
ELEVACIONES = np.array([
    [101.2, 101.8, 102.5, 103.1],
    [100.6, 101.1, 101.9, 102.4],
    [99.8, 100.4, 101.0, 101.7],
    [99.1, 99.7, 100.3, 100.9],
])
```

Donde el terreno está **más alto** que la cota de diseño hay que **cortar** (excavar), y donde está **más bajo** hay que **rellenar**. El volumen de cada celda es la diferencia de altura por el área de la celda.

Escriba un programa en Python con las funciones:

A. `calcular_movimiento(elevaciones: np.ndarray, cota: float, area_celda: float) -> tuple[float, float]`: retorna el volumen total de corte y el de relleno (m³), usando `np.where` para separar las diferencias positivas y negativas.

B. `main() -> None`: solicita la cota de diseño y muestra la matriz de diferencias (redondeada a 2 decimales), los volúmenes de corte y relleno, el **balance** y cuántos **viajes de camión** (de 12 m³) se necesitan para traer o botar el faltante o sobrante. Muestre también la cota que **equilibraría** corte y relleno (el promedio de todas las elevaciones).

**Ejemplos de ejecución**

*Lo que aparece en **negrita** corresponde a lo que digita la persona usuaria.*

<pre>
Cota de diseño (m): <b>101.0</b>

Diferencias respecto a la cota (m):
[[ 0.2  0.8  1.5  2.1]
 [-0.4  0.1  0.9  1.4]
 [-1.2 -0.6  0.   0.7]
 [-1.9 -1.3 -0.7 -0.1]]
Corte: 770.0 m³  Relleno: 620.0 m³
Sobran 150.0 m³: 13 viajes para botar material.
Cota de equilibrio: 101.094 m
</pre>

<pre>
Cota de diseño (m): <b>100.5</b>

Diferencias respecto a la cota (m):
[[ 0.7  1.3  2.   2.6]
 [ 0.1  0.6  1.4  1.9]
 [-0.7 -0.1  0.5  1.2]
 [-1.4 -0.8 -0.2  0.4]]
Corte: 1270.0 m³  Relleno: 320.0 m³
Sobran 950.0 m³: 80 viajes para botar material.
Cota de equilibrio: 101.094 m
</pre>

In [ ]:
#@title Solución
import math
import numpy as np

ELEVACIONES = np.array([
    [101.2, 101.8, 102.5, 103.1],
    [100.6, 101.1, 101.9, 102.4],
    [99.8, 100.4, 101.0, 101.7],
    [99.1, 99.7, 100.3, 100.9],
])
AREA_CELDA_M2 = 10 * 10
CAPACIDAD_CAMION_M3 = 12


def calcular_movimiento(elevaciones: np.ndarray, cota: float, area_celda: float) -> tuple[float, float]:
    """Retorna los volúmenes de corte y de relleno (m³)."""
    diferencias = elevaciones - cota
    corte = np.where(diferencias > 0, diferencias, 0).sum() * area_celda
    relleno = -np.where(diferencias < 0, diferencias, 0).sum() * area_celda
    return corte, relleno


def main() -> None:
    cota = float(input("Cota de diseño (m): "))

    corte, relleno = calcular_movimiento(ELEVACIONES, cota, AREA_CELDA_M2)
    balance = corte - relleno
    viajes = math.ceil(abs(balance) / CAPACIDAD_CAMION_M3)

    print(f"\nDiferencias respecto a la cota (m):\n{np.round(ELEVACIONES - cota, 2)}")
    print(f"Corte: {corte:.1f} m³  Relleno: {relleno:.1f} m³")
    if balance > 0:
        print(f"Sobran {balance:.1f} m³: {viajes} viajes para botar material.")
    else:
        print(f"Faltan {-balance:.1f} m³: {viajes} viajes para traer material.")
    print(f"Cota de equilibrio: {ELEVACIONES.mean():.3f} m")


main()

**Explicación**

`np.where(condición, a, b)` elige elemento por elemento: donde la condición es verdadera toma `a` y donde es falsa toma `b`. Así se separan los cortes (diferencias positivas) de los rellenos (negativas) sin recorrer la matriz. En la cota de equilibrio el material excavado alcanza exactamente para rellenar, y no hay que mover tierra fuera del terreno.

---

<span id="ejercicio-10-13-selecci-n-de-proveedores-de-rodamientos"></span>

## Ejercicio 10.13 — Selección de proveedores de rodamientos

El departamento de compras de una planta evalúa **proveedores de rodamientos** con dos criterios: el **precio** unitario y la **tasa de defectos** (%) observada en compras anteriores:

```python
PROVEEDORES = np.array(["RodaTec", "SKF-CR", "Balín S.A.", "MecaParts", "Orbital"])
PRECIOS = np.array([18.5, 24.0, 15.2, 20.8, 16.9])      # dólares
DEFECTOS = np.array([1.8, 0.4, 3.5, 0.9, 2.2])          # porcentaje
```

Para combinar ambos criterios, se **normaliza** cada uno al rango [0, 1] con $\frac{x - \min}{\max - \min}$ (0 es el mejor valor) y se calcula un **puntaje** ponderado: $p = w \cdot precio_{norm} + (1 - w) \cdot defectos_{norm}$, donde $w$ es el peso del precio. **Menor** puntaje es mejor.

Escriba un programa en Python con las funciones:

A. `normalizar(valores: np.ndarray) -> np.ndarray`

B. `clasificar(precios: np.ndarray, defectos: np.ndarray, peso_precio: float) -> tuple[np.ndarray, np.ndarray]`: retorna los puntajes y los **índices** de los proveedores ordenados de mejor a peor (con `np.argsort`).

C. `main() -> None`: solicita el peso del precio (entre 0 y 1) y muestra el ranking con el nombre, el precio, los defectos y el puntaje (3 decimales). Muestre también el **costo efectivo** de cada proveedor (el precio dividido entre la fracción de piezas buenas), ordenado de menor a mayor con `np.sort`.

**Ejemplos de ejecución**

*Lo que aparece en **negrita** corresponde a lo que digita la persona usuaria.*

<pre>
Peso del precio (0 a 1): <b>0.5</b>

Puesto  Proveedor    Precio  Defectos  Puntaje
     1  Orbital      16.90      2.2%    0.387
     2  MecaParts    20.80      0.9%    0.399
     3  RodaTec      18.50      1.8%    0.413
     4  SKF-CR       24.00      0.4%    0.500
     5  Balín S.A.   15.20      3.5%    0.500

Costos efectivos ordenados ($): [15.75 17.28 18.84 20.99 24.1 ]
Menor costo efectivo: Balín S.A.
</pre>

<pre>
Peso del precio (0 a 1): <b>0.8</b>

Puesto  Proveedor    Precio  Defectos  Puntaje
     1  Balín S.A.   15.20      3.5%    0.200
     2  Orbital      16.90      2.2%    0.271
     3  RodaTec      18.50      1.8%    0.390
     4  MecaParts    20.80      0.9%    0.541
     5  SKF-CR       24.00      0.4%    0.800

Costos efectivos ordenados ($): [15.75 17.28 18.84 20.99 24.1 ]
Menor costo efectivo: Balín S.A.
</pre>

In [ ]:
#@title Solución
import numpy as np

PROVEEDORES = np.array(["RodaTec", "SKF-CR", "Balín S.A.", "MecaParts", "Orbital"])
PRECIOS = np.array([18.5, 24.0, 15.2, 20.8, 16.9])
DEFECTOS = np.array([1.8, 0.4, 3.5, 0.9, 2.2])


def normalizar(valores: np.ndarray) -> np.ndarray:
    """Escala los valores al rango [0, 1]."""
    return (valores - valores.min()) / (valores.max() - valores.min())


def clasificar(precios: np.ndarray, defectos: np.ndarray, peso_precio: float) -> tuple[np.ndarray, np.ndarray]:
    """Retorna los puntajes y los índices ordenados de mejor a peor."""
    puntajes = peso_precio * normalizar(precios) + (1 - peso_precio) * normalizar(defectos)
    return puntajes, np.argsort(puntajes)


def main() -> None:
    peso_precio = float(input("Peso del precio (0 a 1): "))

    puntajes, orden = clasificar(PRECIOS, DEFECTOS, peso_precio)
    print("\nPuesto  Proveedor    Precio  Defectos  Puntaje")
    for puesto, indice in enumerate(orden, start=1):
        print(f"{puesto:6d}  {PROVEEDORES[indice]:<11}{PRECIOS[indice]:7.2f}"
              f"{DEFECTOS[indice]:9.1f}%{puntajes[indice]:9.3f}")

    costo_efectivo = PRECIOS / (1 - DEFECTOS / 100)
    print(f"\nCostos efectivos ordenados ($): {np.round(np.sort(costo_efectivo), 2)}")
    print(f"Menor costo efectivo: {PROVEEDORES[np.argmin(costo_efectivo)]}")


main()

**Explicación**

`np.sort` retorna los **valores** ordenados, mientras que `np.argsort` retorna las **posiciones** que tendrían que tomarse para ordenarlos. Con las posiciones se puede ordenar **cualquier** otro arreglo en el mismo orden (nombres, precios, defectos), algo que `np.sort` no permite. El ranking cambia según el peso: es una decisión de ingeniería, no solo de programación.

---

<span id="ejercicio-10-14-evoluci-n-de-la-resistencia-del-concreto"></span>

## Ejercicio 10.14 — Evolución de la resistencia del concreto

Un laboratorio ensaya **cilindros de concreto** de cuatro mezclas distintas a los 7, 14 y 28 días. La resistencia (MPa) se guarda en una matriz donde cada **fila** es una mezcla y cada **columna** una edad:

```python
MEZCLAS = ["M-1", "M-2", "M-3", "M-4"]
EDADES = np.array([7, 14, 28])
RESISTENCIAS = np.array([
    [15.8, 21.4, 27.9],
    [19.2, 25.6, 31.4],
    [12.1, 17.9, 23.8],
    [21.5, 27.8, 33.9],
])
```

Escriba un programa en Python con las funciones:

A. `porcentaje_de_resistencia_final(resistencias: np.ndarray) -> np.ndarray`: divide cada fila entre su resistencia a los 28 días **usando broadcasting** (la última columna, con forma `(4, 1)`) y retorna la matriz de porcentajes.

B. `mezclas_que_cumplen(resistencias: np.ndarray, especificada: float) -> np.ndarray`: índices de las mezclas cuya resistencia a los 28 días alcanza la especificada.

C. `main() -> None`: solicita la resistencia especificada $f'_c$ (MPa) y muestra el promedio de cada edad (`axis=0`), la matriz de porcentajes (1 decimal), las mezclas que cumplen y, para cada una, el **margen** sobre la especificada.

**Ejemplo de ejecución**

*Lo que aparece en **negrita** corresponde a lo que digita la persona usuaria.*

<pre>
Resistencia especificada f&#x27;c (MPa): <b>28</b>
Promedio a los 7 días: 17.15 MPa
Promedio a los 14 días: 23.18 MPa
Promedio a los 28 días: 29.25 MPa

Porcentaje de la resistencia final (filas = mezclas):
[[ 56.6  76.7 100. ]
 [ 61.1  81.5 100. ]
 [ 50.8  75.2 100. ]
 [ 63.4  82.  100. ]]

Mezclas que cumplen f&#x27;c = 28.0 MPa: [&#x27;M-2&#x27; &#x27;M-4&#x27;]
  M-2: margen de 3.4 MPa
  M-4: margen de 5.9 MPa
</pre>

**Pregunta de respuesta corta**

¿Qué pasaría si se escribiera `RESISTENCIAS / RESISTENCIAS[:, -1]` sin el `reshape(-1, 1)`?

In [ ]:
#@title Solución
import numpy as np

MEZCLAS = np.array(["M-1", "M-2", "M-3", "M-4"])
EDADES = np.array([7, 14, 28])
RESISTENCIAS = np.array([
    [15.8, 21.4, 27.9],
    [19.2, 25.6, 31.4],
    [12.1, 17.9, 23.8],
    [21.5, 27.8, 33.9],
])


def porcentaje_de_resistencia_final(resistencias: np.ndarray) -> np.ndarray:
    """Porcentaje de la resistencia a 28 días alcanzado en cada edad."""
    resistencia_final = resistencias[:, -1].reshape(-1, 1)
    return resistencias / resistencia_final * 100


def mezclas_que_cumplen(resistencias: np.ndarray, especificada: float) -> np.ndarray:
    """Índices de las mezclas que alcanzan la resistencia especificada a 28 días."""
    return np.where(resistencias[:, -1] >= especificada)[0]


def main() -> None:
    especificada = float(input("Resistencia especificada f'c (MPa): "))

    promedios = RESISTENCIAS.mean(axis=0)
    porcentajes = porcentaje_de_resistencia_final(RESISTENCIAS)
    cumplen = mezclas_que_cumplen(RESISTENCIAS, especificada)

    for edad, promedio in zip(EDADES, promedios):
        print(f"Promedio a los {edad} días: {promedio:.2f} MPa")
    print(f"\nPorcentaje de la resistencia final (filas = mezclas):\n{np.round(porcentajes, 1)}")
    print(f"\nMezclas que cumplen f'c = {especificada} MPa: {MEZCLAS[cumplen]}")
    for indice in cumplen:
        margen = RESISTENCIAS[indice, -1] - especificada
        print(f"  {MEZCLAS[indice]}: margen de {margen:.1f} MPa")


main()

**Explicación**

**Respuesta corta:** `RESISTENCIAS[:, -1]` tiene forma `(4,)` y NumPy intentaría alinearla con las **columnas** de la matriz `(4, 3)`: como 4 ≠ 3, se produciría un `ValueError: operands could not be broadcast together`. Con `reshape(-1, 1)` se convierte en una **columna** `(4, 1)`, que se repite a lo largo de las 3 columnas: cada fila se divide entre su propio valor.

---

<span id="ejercicio-10-15-tolerancias-acumuladas-en-un-ensamble"></span>

## Ejercicio 10.15 — Tolerancias acumuladas en un ensamble

Un eje se ensambla con **tres piezas** en serie (un buje, un separador y un rodamiento), y la longitud total del conjunto debe estar entre **79.8 y 80.2 mm**. Cada pieza se fabrica con variaciones que siguen una distribución normal:

| Pieza | Media (mm) | Desviación estándar (mm) |
| :-- | :-: | :-: |
| Buje | 25.0 | 0.05 |
| Separador | 30.0 | 0.08 |
| Rodamiento | 25.0 | 0.06 |

En lugar de fabricar miles de piezas de prueba, se **simula** el proceso con números aleatorios.

Escriba un programa en Python que use NumPy y:

A. Defina `simular_ensambles(cantidad: int) -> np.ndarray`, que genera con `np.random.normal` un arreglo para cada pieza y retorna la **suma** (la longitud de cada ensamble). Fije la semilla con `np.random.seed(10)` en `main()`.

B. En `main()`, solicite la cantidad de ensambles a simular y muestre la media y la desviación estándar de las longitudes (4 decimales), las longitudes mínima y máxima, el porcentaje de ensambles **fuera de tolerancia** (separando los demasiado cortos y los demasiado largos) y la desviación estándar teórica $\sqrt{0.05^2 + 0.08^2 + 0.06^2}$ para compararla.

**Ejemplo de ejecución**

*Lo que aparece en **negrita** corresponde a lo que digita la persona usuaria.*

<pre>
Cantidad de ensambles a simular: <b>100000</b>

Longitud media: 79.9999 mm
Desviación estándar simulada: 0.1119 mm (teórica 0.1118 mm)
Mínima: 79.543 mm  Máxima: 80.472 mm
Demasiado cortos: 3.71%
Demasiado largos: 3.66%
Fuera de tolerancia: 7.37%
</pre>

In [ ]:
#@title Solución
import numpy as np

MEDIAS = [25.0, 30.0, 25.0]
DESVIACIONES = [0.05, 0.08, 0.06]
LONGITUD_MINIMA = 79.8
LONGITUD_MAXIMA = 80.2


def simular_ensambles(cantidad: int) -> np.ndarray:
    """Simula la longitud total de los ensambles."""
    buje = np.random.normal(MEDIAS[0], DESVIACIONES[0], cantidad)
    separador = np.random.normal(MEDIAS[1], DESVIACIONES[1], cantidad)
    rodamiento = np.random.normal(MEDIAS[2], DESVIACIONES[2], cantidad)
    return buje + separador + rodamiento


def main() -> None:
    np.random.seed(10)
    cantidad = int(input("Cantidad de ensambles a simular: "))

    longitudes = simular_ensambles(cantidad)
    cortos = np.sum(longitudes < LONGITUD_MINIMA)
    largos = np.sum(longitudes > LONGITUD_MAXIMA)
    desviacion_teorica = np.sqrt(np.sum(np.array(DESVIACIONES) ** 2))

    print(f"\nLongitud media: {longitudes.mean():.4f} mm")
    print(f"Desviación estándar simulada: {longitudes.std():.4f} mm (teórica {desviacion_teorica:.4f} mm)")
    print(f"Mínima: {longitudes.min():.3f} mm  Máxima: {longitudes.max():.3f} mm")
    print(f"Demasiado cortos: {cortos / cantidad:.2%}")
    print(f"Demasiado largos: {largos / cantidad:.2%}")
    print(f"Fuera de tolerancia: {(cortos + largos) / cantidad:.2%}")


main()

**Explicación**

`np.sum(longitudes < LONGITUD_MINIMA)` cuenta cuántos elementos cumplen la condición, porque suma los `True` como 1. La simulación confirma una regla importante del diseño mecánico: las desviaciones **no se suman directamente** (0.05 + 0.08 + 0.06 = 0.19 mm), sino como la raíz de la suma de sus cuadrados (≈ 0.112 mm).

---

<span id="ejercicio-10-16-calibraci-n-de-un-aceler-metro-de-tres-ejes"></span>

## Ejercicio 10.16 — Calibración de un acelerómetro de tres ejes

Un **acelerómetro de tres ejes** no es perfecto: además de la sensibilidad de cada eje, cada eje "siente" un poco la aceleración de los otros (**sensibilidad cruzada**). Un ensayo de calibración determinó la **matriz de sensibilidad** $S$ (mV por g), que relaciona la aceleración real con la lectura: $lectura = S \cdot a$.

```python
SENSIBILIDAD = np.array([
    [102.0, 1.8, -0.9],
    [2.1, 98.5, 1.2],
    [-1.4, 0.7, 101.3],
])
```

Para recuperar la aceleración real a partir de las lecturas, se usa la **inversa**: $a = S^{-1} \cdot lectura$.

Escriba un programa en Python con las funciones:

A. `corregir_lecturas(lecturas: np.ndarray, sensibilidad: np.ndarray) -> np.ndarray`: `lecturas` es una matriz de forma `(n, 3)` (una fila por medición). Use la inversa (`np.linalg.inv`) y el producto matricial para corregir **todas** las filas a la vez.

B. `main() -> None`: muestra la diagonal de $S$ (`np.diag`), es decir, la sensibilidad principal de cada eje; solicita la cantidad de mediciones y cada lectura `x y z` (mV); muestra las aceleraciones **corregidas** (g, 3 decimales), las que se obtendrían dividiendo **solo** entre la diagonal (sin corregir la sensibilidad cruzada) y la **magnitud** de cada aceleración corregida.

**Ejemplo de ejecución**

*Lo que aparece en **negrita** corresponde a lo que digita la persona usuaria.*

<pre>
Sensibilidad principal por eje (mV/g): [102.   98.5 101.3]
Cantidad de mediciones: <b>3</b>
Lectura 1 (x y z en mV): <b>-0.9 1.2 101.3</b>
Lectura 2 (x y z en mV): <b>100.2 3.9 -2.3</b>
Lectura 3 (x y z en mV): <b>73.5 70.9 -0.4</b>

Aceleraciones corregidas (g):
[[-0.    -0.     1.   ]
 [ 0.982  0.019 -0.009]
 [ 0.708  0.705  0.001]]
Dividiendo solo entre la diagonal (g):
[[-0.009  0.012  1.   ]
 [ 0.982  0.04  -0.023]
 [ 0.721  0.72  -0.004]]
Magnitud de cada aceleración corregida (g): [1.    0.982 0.999]
</pre>

In [ ]:
#@title Solución
import numpy as np

SENSIBILIDAD = np.array([
    [102.0, 1.8, -0.9],
    [2.1, 98.5, 1.2],
    [-1.4, 0.7, 101.3],
])


def corregir_lecturas(lecturas: np.ndarray, sensibilidad: np.ndarray) -> np.ndarray:
    """Convierte lecturas (mV) en aceleraciones (g) usando la inversa de la sensibilidad."""
    return lecturas @ np.linalg.inv(sensibilidad).T


def main() -> None:
    diagonal = np.diag(SENSIBILIDAD)
    print(f"Sensibilidad principal por eje (mV/g): {diagonal}")

    cantidad = int(input("Cantidad de mediciones: "))
    filas = []
    for numero in range(1, cantidad + 1):
        filas.append(input(f"Lectura {numero} (x y z en mV): ").split())
    lecturas = np.array(filas, dtype=float)

    np.set_printoptions(suppress=True)
    corregidas = corregir_lecturas(lecturas, SENSIBILIDAD)
    sin_corregir = lecturas / diagonal
    magnitudes = np.sqrt(np.sum(corregidas ** 2, axis=1))

    print(f"\nAceleraciones corregidas (g):\n{np.round(corregidas, 3)}")
    print(f"Dividiendo solo entre la diagonal (g):\n{np.round(sin_corregir, 3)}")
    print(f"Magnitud de cada aceleración corregida (g): {np.round(magnitudes, 3)}")


main()

**Explicación**

La primera lectura corresponde al sensor **en reposo** con el eje z hacia arriba: la aceleración corregida debe ser (0, 0, 1) g, y el programa lo confirma. `np.set_printoptions(suppress=True)` evita que NumPy muestre los arreglos en notación científica. Dividir solo entre la diagonal deja pequeños errores en los otros ejes, que en aplicaciones como la navegación inercial se acumulan rápidamente. Como cada medición es una **fila**, la fórmula $S^{-1} \cdot lectura$ se aplica a todas a la vez con `lecturas @ inv(S).T`.

---

<span id="ejercicio-10-17-revisi-n-de-una-matriz-de-rigidez"></span>

## Ejercicio 10.17 — Revisión de una matriz de rigidez

En el **método de elementos finitos**, el comportamiento de una estructura se describe con una **matriz de rigidez** $K$. Antes de usarla, un programa de análisis estructural verifica tres propiedades:

1. **Simetría:** $K = K^T$.
2. **Diagonal positiva:** todos los elementos de la diagonal son mayores que cero.
3. **No singular:** su determinante es distinto de cero (si no, la estructura es un *mecanismo* y no tiene solución).

Para una estructura de resortes en serie de rigideces $k_1, k_2, ..., k_n$ empotrada en un extremo, la matriz es **tridiagonal**: $K_{ii} = k_i + k_{i+1}$ (con $k_{n+1} = 0$) y $K_{i,i+1} = K_{i+1,i} = -k_{i+1}$.

Escriba un programa en Python con las funciones:

A. `construir_matriz(rigideces: np.ndarray) -> np.ndarray` (use `np.zeros` y un ciclo sobre los índices).

B. `revisar_matriz(matriz: np.ndarray) -> tuple[bool, bool, bool]`

C. `main() -> None`: solicita las rigideces (kN/mm) en una línea y las cargas aplicadas en cada nodo (kN); muestra la matriz, el resultado de cada verificación y, si la matriz es válida, los **desplazamientos** de cada nodo (mm, 3 decimales) resolviendo $K \cdot u = F$.

**Ejemplos de ejecución**

*Lo que aparece en **negrita** corresponde a lo que digita la persona usuaria.*

<pre>
Rigideces k1..kn (kN/mm): <b>40 25 30</b>
Cargas en cada nodo (kN): <b>0 0 12</b>

Matriz de rigidez:
[[ 65. -25.   0.]
 [-25.  55. -30.]
 [  0. -30.  30.]]
¿Simétrica?: True
¿Diagonal positiva?: True
¿No singular?: True
Desplazamientos (mm): [0.3  0.78 1.18]
</pre>

<pre>
Rigideces k1..kn (kN/mm): <b>40 0 30</b>
Cargas en cada nodo (kN): <b>0 0 12</b>

Matriz de rigidez:
[[ 40.  -0.   0.]
 [ -0.  30. -30.]
 [  0. -30.  30.]]
¿Simétrica?: True
¿Diagonal positiva?: True
¿No singular?: False
La matriz no es válida: revise el modelo.
</pre>

In [ ]:
#@title Solución
import numpy as np


def construir_matriz(rigideces: np.ndarray) -> np.ndarray:
    """Construye la matriz de rigidez tridiagonal de resortes en serie."""
    cantidad = len(rigideces)
    matriz = np.zeros((cantidad, cantidad))
    for i in range(cantidad):
        matriz[i, i] = rigideces[i]
        if i + 1 < cantidad:
            matriz[i, i] += rigideces[i + 1]
            matriz[i, i + 1] = -rigideces[i + 1]
            matriz[i + 1, i] = -rigideces[i + 1]
    return matriz


def revisar_matriz(matriz: np.ndarray) -> tuple[bool, bool, bool]:
    """Verifica simetría, diagonal positiva y que la matriz no sea singular."""
    simetrica = np.allclose(matriz, matriz.T)
    diagonal_positiva = np.all(np.diag(matriz) > 0)
    no_singular = not np.isclose(np.linalg.det(matriz), 0)
    return bool(simetrica), bool(diagonal_positiva), no_singular


def main() -> None:
    rigideces = np.array(input("Rigideces k1..kn (kN/mm): ").split(), dtype=float)
    cargas = np.array(input("Cargas en cada nodo (kN): ").split(), dtype=float)

    matriz = construir_matriz(rigideces)
    simetrica, diagonal_positiva, no_singular = revisar_matriz(matriz)

    print(f"\nMatriz de rigidez:\n{matriz}")
    print(f"¿Simétrica?: {simetrica}")
    print(f"¿Diagonal positiva?: {diagonal_positiva}")
    print(f"¿No singular?: {no_singular}")

    if simetrica and diagonal_positiva and no_singular:
        desplazamientos = np.linalg.solve(matriz, cargas)
        print(f"Desplazamientos (mm): {np.round(desplazamientos, 3)}")
    else:
        print("La matriz no es válida: revise el modelo.")


main()

**Explicación**

Con una rigidez de 0 en el segundo resorte, la estructura queda "desconectada" y el determinante es 0: no existe una única solución, y `np.linalg.solve` lanzaría un `LinAlgError`. Verificar las propiedades **antes** de resolver permite dar un mensaje claro. En el primer caso, como la carga está solo en el extremo, cada resorte transmite los 12 kN completos y el desplazamiento del nodo 3 es $12/40 + 12/25 + 12/30 = 1.18$ mm.

---

<span id="ejercicio-10-18-valor-eficaz-de-un-voltaje-alterno"></span>

## Ejercicio 10.18 — Valor eficaz de un voltaje alterno

Un técnico usa un osciloscopio digital para analizar el voltaje de un tomacorriente. El voltaje alterno ideal es:

$$v(t) = V_p \sin(2\pi f t)$$

donde $V_p$ es el voltaje pico y $f$ la frecuencia (60 Hz en Costa Rica). El **valor eficaz** (RMS), que es el que indica un multímetro, se calcula con las muestras como:

$$V_{rms} = \sqrt{\frac{1}{N} \sum v_i^2}$$

y para una senoide pura debe ser $V_p / \sqrt{2}$. Un voltaje con **distorsión armónica** agrega una componente de tercera armónica: $v(t) = V_p \sin(2\pi f t) + V_3 \sin(2\pi \cdot 3f \cdot t)$.

Escriba un programa en Python con las funciones:

A. `generar_senal(voltaje_pico: float, amplitud_tercera: float, frecuencia: float, muestras: int) -> tuple[np.ndarray, np.ndarray]`: genera exactamente **un periodo** de la señal con `np.linspace(0, 1 / frecuencia, muestras, endpoint=False)`.

B. `calcular_rms(senal: np.ndarray) -> float`

C. `main() -> None`: solicita $V_p$, $V_3$ y la cantidad de muestras; muestra el voltaje pico medido, el RMS calculado, el RMS teórico de la senoide pura ($V_p/\sqrt{2}$), el **factor de cresta** (pico / RMS, que vale $\sqrt{2} \approx 1.414$ para una senoide pura) y la **distorsión** $THD = V_3 / V_p$ (%).

**Ejemplos de ejecución**

*Lo que aparece en **negrita** corresponde a lo que digita la persona usuaria.*

<pre>
Voltaje pico de la fundamental (V): <b>169.7</b>
Amplitud de la tercera armónica (V): <b>0</b>
Muestras por periodo: <b>1000</b>

Periodo: 16.667 ms con 1000 muestras
Voltaje pico medido: 169.70 V
RMS calculado: 120.00 V (senoide pura: 120.00 V)
Factor de cresta: 1.414
THD: 0.0%
</pre>

<pre>
Voltaje pico de la fundamental (V): <b>169.7</b>
Amplitud de la tercera armónica (V): <b>25</b>
Muestras por periodo: <b>1000</b>

Periodo: 16.667 ms con 1000 muestras
Voltaje pico medido: 147.33 V
RMS calculado: 121.29 V (senoide pura: 120.00 V)
Factor de cresta: 1.215
THD: 14.7%
</pre>

In [ ]:
#@title Solución
import numpy as np

FRECUENCIA_HZ = 60


def generar_senal(voltaje_pico: float, amplitud_tercera: float, frecuencia: float,
                  muestras: int) -> tuple[np.ndarray, np.ndarray]:
    """Genera un periodo de un voltaje senoidal con tercera armónica."""
    tiempo = np.linspace(0, 1 / frecuencia, muestras, endpoint=False)
    voltaje = (voltaje_pico * np.sin(2 * np.pi * frecuencia * tiempo)
               + amplitud_tercera * np.sin(2 * np.pi * 3 * frecuencia * tiempo))
    return tiempo, voltaje


def calcular_rms(senal: np.ndarray) -> float:
    """Calcula el valor eficaz de una señal muestreada."""
    return float(np.sqrt(np.mean(senal ** 2)))


def main() -> None:
    voltaje_pico = float(input("Voltaje pico de la fundamental (V): "))
    amplitud_tercera = float(input("Amplitud de la tercera armónica (V): "))
    muestras = int(input("Muestras por periodo: "))

    tiempo, voltaje = generar_senal(voltaje_pico, amplitud_tercera, FRECUENCIA_HZ, muestras)
    rms = calcular_rms(voltaje)
    pico = np.abs(voltaje).max()

    print(f"\nPeriodo: {tiempo[-1] * 1000 + 1000 / (FRECUENCIA_HZ * muestras):.3f} ms con {tiempo.size} muestras")
    print(f"Voltaje pico medido: {pico:.2f} V")
    print(f"RMS calculado: {rms:.2f} V (senoide pura: {voltaje_pico / np.sqrt(2):.2f} V)")
    print(f"Factor de cresta: {pico / rms:.3f}")
    print(f"THD: {amplitud_tercera / voltaje_pico:.1%}")


main()

**Explicación**

`np.sin` y `np.sqrt` son **funciones vectoriales**: se aplican a cada elemento del arreglo, a diferencia de `math.sin`, que solo acepta un número. Con $V_p = 169.7$ V se obtiene el conocido valor de **120 V RMS**. La distorsión armónica cambia la forma de la onda y, con ello, su pico y su factor de cresta, lo que puede confundir a los multímetros que asumen una senoide pura.

---

<span id="ejercicio-10-19-interpolaci-n-en-una-tabla-de-vapor"></span>

## Ejercicio 10.19 — Interpolación en una tabla de vapor

Un ingeniero mecánico diseña una caldera y necesita la **entalpía** del vapor saturado a temperaturas que no aparecen en su tabla termodinámica. La tabla disponible es:

```python
TEMPERATURAS_C = np.array([100, 120, 140, 160, 180, 200])
PRESIONES_KPA = np.array([101.4, 198.7, 361.5, 618.2, 1002.8, 1554.9])
ENTALPIAS_KJ_KG = np.array([2675.6, 2705.9, 2733.5, 2757.4, 2777.2, 2792.0])
```

Lea la documentación de `np.interp` (`help(np.interp)`) y escriba un programa en Python que:

A. Defina `interpolar_propiedades(temperaturas: np.ndarray) -> tuple[np.ndarray, np.ndarray]`, que retorna la presión y la entalpía interpoladas **linealmente** para un arreglo de temperaturas.

B. En `main()`, solicite varias temperaturas en una sola línea, **descarte** (con una máscara) las que estén fuera del rango de la tabla (indicando cuáles), y muestre una tabla con la presión y la entalpía interpoladas. Calcule también el **calor** necesario para producir 1500 kg/h de vapor a la temperatura más alta ingresada, partiendo de agua a 25 °C (entalpía de 104.8 kJ/kg), en kW.

**Ejemplo de ejecución**

*Lo que aparece en **negrita** corresponde a lo que digita la persona usuaria.*

<pre>
Temperaturas de interés (°C): <b>135 172.5 95 150 210 188</b>
Fuera del rango de la tabla (se descartan): [ 95. 210.]

 T (°C)   P (kPa)   h (kJ/kg)
  135.0     320.8      2726.6
  172.5     858.6      2769.8
  150.0     489.9      2745.4
  188.0    1223.6      2783.1

Calor para 1500 kg/h de vapor a 188.0 °C: 1,116.0 kW
</pre>

**Pregunta de respuesta corta**

Según la documentación, ¿qué retorna `np.interp` si la temperatura está **fuera** del rango de la tabla? ¿Por qué es peligroso no descartar esos valores?

In [ ]:
#@title Solución
import numpy as np

TEMPERATURAS_C = np.array([100, 120, 140, 160, 180, 200])
PRESIONES_KPA = np.array([101.4, 198.7, 361.5, 618.2, 1002.8, 1554.9])
ENTALPIAS_KJ_KG = np.array([2675.6, 2705.9, 2733.5, 2757.4, 2777.2, 2792.0])
ENTALPIA_AGUA_25C = 104.8
FLUJO_VAPOR_KG_H = 1500


def interpolar_propiedades(temperaturas: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """Interpola linealmente la presión y la entalpía del vapor saturado."""
    presiones = np.interp(temperaturas, TEMPERATURAS_C, PRESIONES_KPA)
    entalpias = np.interp(temperaturas, TEMPERATURAS_C, ENTALPIAS_KJ_KG)
    return presiones, entalpias


def main() -> None:
    temperaturas = np.array(input("Temperaturas de interés (°C): ").split(), dtype=float)

    dentro = (temperaturas >= TEMPERATURAS_C.min()) & (temperaturas <= TEMPERATURAS_C.max())
    if np.any(~dentro):
        print(f"Fuera del rango de la tabla (se descartan): {temperaturas[~dentro]}")

    validas = temperaturas[dentro]
    presiones, entalpias = interpolar_propiedades(validas)

    print("\n T (°C)   P (kPa)   h (kJ/kg)")
    for temperatura, presion, entalpia in zip(validas, presiones, entalpias):
        print(f"{temperatura:7.1f}{presion:10.1f}{entalpia:12.1f}")

    entalpia_maxima = entalpias[np.argmax(validas)]
    calor_kw = FLUJO_VAPOR_KG_H / 3600 * (entalpia_maxima - ENTALPIA_AGUA_25C)
    print(f"\nCalor para {FLUJO_VAPOR_KG_H} kg/h de vapor a {validas.max()} °C: {calor_kw:,.1f} kW")


main()

**Explicación**

**Respuesta corta:** `np.interp` **no** lanza un error: retorna el valor del **extremo** más cercano de la tabla (por ejemplo, la entalpía a 200 °C para cualquier temperatura mayor). El programa daría un resultado aparentemente válido pero incorrecto, sin ninguna advertencia. El operador `~` niega una máscara booleana elemento a elemento.

---

<span id="ejercicio-10-20-monitoreo-estructural-de-un-puente"></span>

## Ejercicio 10.20 — Monitoreo estructural de un puente

Un puente vehicular tiene **5 galgas extensométricas** que miden la deformación del acero durante el paso de vehículos pesados. Cada galga entrega un voltaje (mV) que debe convertirse a deformación con su **factor de calibración** propio (µε por mV) y su **offset** (lectura en reposo, en mV):

$$\varepsilon = (lectura - offset) \cdot factor \qquad \sigma = E \cdot \varepsilon \cdot 10^{-6}$$

con $E = 200\,000$ MPa. Las lecturas se guardan en una matriz: cada **fila** es un instante de tiempo y cada **columna** una galga.

```python
FACTORES = np.array([52.1, 49.8, 51.3, 50.6, 48.9])   # µε/mV
OFFSETS = np.array([0.12, -0.05, 0.08, 0.02, -0.10])   # mV
```

Escriba un programa en Python con las funciones:

A. `convertir_a_esfuerzos(lecturas: np.ndarray) -> np.ndarray`: convierte **toda** la matriz a esfuerzos (MPa) con *broadcasting* (los factores y offsets se aplican a cada fila).

B. `resumir_galgas(esfuerzos: np.ndarray) -> tuple[np.ndarray, np.ndarray, np.ndarray]`: esfuerzo máximo, promedio y el **instante** del máximo de cada galga (`axis=0`).

C. `main() -> None`: solicita la cantidad de instantes y la lectura de las 5 galgas en cada uno. Muestra la matriz de esfuerzos (1 decimal), el resumen por galga, las galgas ordenadas de **más a menos** cargada (use `np.argsort` y `[::-1]`), y cuántos instantes tuvieron **alguna** galga por encima del **límite de alerta de 60 MPa** (use `np.any(..., axis=1)`).

**Ejemplo de ejecución**

*Lo que aparece en **negrita** corresponde a lo que digita la persona usuaria.*

<pre>
Cantidad de instantes: <b>4</b>
Instante 1 - lecturas de las 5 galgas (mV): <b>2.10 3.40 5.20 4.10 1.80</b>
Instante 2 - lecturas de las 5 galgas (mV): <b>3.60 5.80 6.10 5.30 2.90</b>
Instante 3 - lecturas de las 5 galgas (mV): <b>4.20 6.30 5.40 4.80 3.30</b>
Instante 4 - lecturas de las 5 galgas (mV): <b>1.90 2.80 3.10 2.60 1.50</b>

Esfuerzos (MPa), filas = instantes, columnas = galgas:
[[20.6 34.4 52.5 41.3 18.6]
 [36.3 58.3 61.8 53.4 29.3]
 [42.5 63.2 54.6 48.4 33.3]
 [18.5 28.4 31.  26.1 15.6]]

Galga  Máximo  Promedio  Instante del máximo
    1    42.5      29.5           3
    2    63.2      46.1           3
    3    61.8      50.0           2
    4    53.4      42.3           2
    5    33.3      24.2           3

Galgas de más a menos cargada: [2 3 4 1 5]
Instantes con alguna galga sobre 60 MPa: 2 [2 3]
</pre>

In [ ]:
#@title Solución
import numpy as np

FACTORES = np.array([52.1, 49.8, 51.3, 50.6, 48.9])
OFFSETS = np.array([0.12, -0.05, 0.08, 0.02, -0.10])
MODULO_ELASTICIDAD_MPA = 200000
LIMITE_ALERTA_MPA = 60


def convertir_a_esfuerzos(lecturas: np.ndarray) -> np.ndarray:
    """Convierte las lecturas (mV) de todas las galgas a esfuerzos (MPa)."""
    deformaciones = (lecturas - OFFSETS) * FACTORES
    return MODULO_ELASTICIDAD_MPA * deformaciones * 1e-6


def resumir_galgas(esfuerzos: np.ndarray) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Esfuerzo máximo, promedio e instante del máximo de cada galga."""
    return esfuerzos.max(axis=0), esfuerzos.mean(axis=0), esfuerzos.argmax(axis=0)


def main() -> None:
    instantes = int(input("Cantidad de instantes: "))
    filas = []
    for numero in range(1, instantes + 1):
        filas.append(input(f"Instante {numero} - lecturas de las 5 galgas (mV): ").split())
    lecturas = np.array(filas, dtype=float)

    esfuerzos = convertir_a_esfuerzos(lecturas)
    maximos, promedios, instantes_maximo = resumir_galgas(esfuerzos)
    orden = np.argsort(maximos)[::-1]
    instantes_en_alerta = np.any(esfuerzos > LIMITE_ALERTA_MPA, axis=1)

    print(f"\nEsfuerzos (MPa), filas = instantes, columnas = galgas:\n{np.round(esfuerzos, 1)}")
    print("\nGalga  Máximo  Promedio  Instante del máximo")
    for galga in range(len(FACTORES)):
        print(f"{galga + 1:5d}{maximos[galga]:8.1f}{promedios[galga]:10.1f}{instantes_maximo[galga] + 1:12d}")
    print(f"\nGalgas de más a menos cargada: {orden + 1}")
    print(f"Instantes con alguna galga sobre {LIMITE_ALERTA_MPA} MPa: {instantes_en_alerta.sum()} "
          f"{np.arange(1, instantes + 1)[instantes_en_alerta]}")


main()

**Explicación**

La resta `lecturas - OFFSETS` combina una matriz `(4, 5)` con un vector `(5,)`: por *broadcasting*, el vector se aplica a **cada fila**, de modo que cada columna (galga) usa su propio offset y su propio factor. Invertir el resultado de `np.argsort` con `[::-1]` da el orden de mayor a menor.